### ISSUE TITLE
05 - Powershell Error Log : Hard-coded references

### ISSUE THREAD

**Issue by amtwo** [sqlcollaborative/dbareports#10]
Report text references "DBA Database" -- this should be updated to be "dbareports database".

Report text references "Scripts running on " -- This should be updated to use the proper dbareports server. Given that the report is pulling from that server, we should be able to use @@SERVERNAME to grab the DB Instance name.

Report text references "" -- this should be updated to grab the configured log path.  

The report text is a hyperlink that links to file://  This should be updated to be the configured log path.

**Comment by SQLDBAWithABeard** [comment]
Fixed in releases last week
