### ISSUE TITLE
Problem creating ProxyAccount within the installation

### ISSUE THREAD

**Issue by PsPsam** [sqlcollaborative/dbareports#11]
PS C:\Install> Install-DbaReports -SqlServer xxx-yyy -InstallPath c:\DbaReports
No log file path specified, using c:\DbaReports\logs

The install database, dbareports, does not exist. Create?
Would you like us to create a database named dbareports on xxx-yyy(Y/N)
[Y] Yes  [N] No  [?] Help (default is "Y"): y
Writing config to C:\Users\adm-user\Documents\WindowsPowerShell\Modules\dbareports\dbareports-config.json
WARNING: The Agent account, NT Service\SQLSERVERAGENT, is a local account. It is *highly unlikely* that it will have
permissions to log into other SQL Servers.

You haven't specified a proxy account. The SQL Server Agent service account, NT Service\SQLSERVERAGENT, must have
access to all servers or you can use a proxy account.
 Would you like to create a proxy now? (Y/N)
[Y] Yes  [N] No  [?] Help (default is "Y"): y

xxxx\ads-sql-dbareports does not exist on xxx-yyy.
Adding now as non-privileged login. Continue? (Y/N)
[Y] Yes  [N] No  [?] Help (default is "Y"): y
Created login for xxxx\ads-sql-dbareports
Created credential for xxxx\ads-sql-dbareports as DBAreports
Created Proxy Account for credential as 'PowerShell Proxy Account for dbareports'
Added PowerShell and CmdExec subsystems to 'PowerShell Proxy Account for dbareports'
Proxy account not found. Can't continue.
At C:\Program Files\WindowsPowerShell\Modules\dbareports\functions\Install-DbaReports.ps1:964 char:7
+ ...                      throw "Proxy account not found. Can't continue."
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Proxy account not found. Can't continue.:String) [], RuntimeException
    + FullyQualifiedErrorId : Proxy account not found. Can't continue.

**Comment by ctrlbold** [comment]
I bet this will need a .Refresh() or .Alter() somewhere up in thurr

**Comment by ctrlbold** [comment]
Fixed by #30
