### ISSUE TITLE
Database.ps1 error when conencting to server instans

### ISSUE THREAD

**Issue by PsPsam** [sqlcollaborative/dbareports#21]
I had a failure to connect to one server and the script the stopped with an error. I added Try and Catch in the Connect to dbareports server part of the script.
# Connect to dbareports server

```
    try {
        $server = Connect-SqlServer -SqlServer $Connection
```

....

```
            )
        }
    }
    catch {
        Write-Exception $_
        throw "Can't connect to $Connection."
    }
}
```

**Comment by SQLDBAWithABeard** [comment]
will need a continue as well to keep it processing the loop

**Comment by SQLDBAWithABeard** [comment]
resolved in latest release
