### ISSUE TITLE
Can't add a bunch of servers at once

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbareports#22]
This is from the dev branch. 

PS:> Get-SqlRegisteredServerName -SqlServer sql2014 | Add-DbrServerToInventory

Results in the first couple being inserted then...

> C:\github\dbareports\functions\SharedFunctions.ps1
> At C:\github\dbareports\functions\SharedFunctions.ps1:850 char:2
> -     $null = $cmd.ExecuteNonQuery()
> -     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   System.Management.Automation.MethodInvocationException: Exception calling "ExecuteNonQuery" with "0" argument(s): "Conversion failed when converting the nvarchar value 'System.Object[]' to data type int.

Here's the exceptions file. Do we need to do a .Table.Rows, perhaps? Or am I in the wrong branch?
[dbareports-exceptions.txt](https://github.com/SQLDBAWithABeard/dbareports/files/449234/dbareports-exceptions.txt)

**Comment by js0505** [comment]
Interesting, let me see if I get time to take a look at that this morning.  Did not think of utilizing CMS.

**Comment by SQLDBAWithABeard** [comment]
Is this still an issue. I think it is data but not convinced. Will be easier to troubleshoot once better logging written
