### ISSUE TITLE
Should have a CONTRIBUTING.md 

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbareports#33]
Reading this post [https://poshoholic.com/2016/09/30/get-your-powershell-game-on-for-the-hacktoberfest-challenge/](https://poshoholic.com/2016/09/30/get-your-powershell-game-on-for-the-hacktoberfest-challenge/) and then looking at the resources on the [hacktoberfest](https://hacktoberfest.digitalocean.com/#resources) site and also thinking about people who need to contribute and those who have asked me how they start - we should have a CONTRIBUTING.md

**Comment by SmoothJazzMusic** [comment]
Hey what's up @SQLDBAWithABeard, Can I have a grab at this?

**Comment by SQLDBAWithABeard** [comment]
He @SmoothJazzMusic sure, we generally discuss these things in the SQL Server Community Slack channel [https://sqlps.io/slack](https://sqlps.io/slack) for auto invite. There is a #dbareports in there

**Comment by ctrlbold** [comment]
Just added one to dbatools: [CONTRIBUTING.md](https://github.com/sqlcollaborative/dbatools/blob/development/CONTRIBUTING.md)
