### ISSUE TITLE
Databases.ps1 fails - .Where() method

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbareports#40]
Using Databases.ps1 and it fails on PS v3.0 because the .Where() method is not recognized.

`$LastDBCCDate = $dbccresults.rows.Where{$_.Field -eq 'dbi_dbccLastKnownGood'}[0].value`

Need to change to:
`$LastDBCCDate = ($dbccresults | Where-Object {$_.Field -eq 'dbi_dbccLastKnownGood'} | Sort-Object Value -Descending | Select-Object Value -First 1).Value`

Need to sort and select first because 

> "SQL Server 2008R2 has a "bug" that causes each databases to possess two dbi_dbccLastKnownGood fileds, instead of the normal one."

This way, script will only use the newest value.

**Comment by ClaudioESSilva** [comment]
Addressed on commit https://github.com/sqlcollaborative/dbareports/commit/2a57002c308db2d5e339ada9e0ba642e9a380b70

**Comment by SQLDBAWithABeard** [comment]
merged
