### ISSUE TITLE
"dbareports Databases sample.pbix" has explicit database name DBADatabase on 'NotEntered' query

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbareports#41]
Error: "DataSource.Error: Microsoft SQL: Invalid object name 'DBADatabase.dbo.NotEntered'."

Need to remove "DBADatabase."

**Comment by ClaudioESSilva** [comment]
Fixed on commit https://github.com/sqlcollaborative/dbareports/commit/32d3faf8fdcfb1fae62bee0209049b10cadd0dc4

**Comment by SQLDBAWithABeard** [comment]
merged
