### ISSUE TITLE
"dbareports Databases sample.pbix" Typo 'Numbner' istead of 'Number'

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbareports#42]
Typo 'Numbner' istead of 'Number'
![image](https://cloud.githubusercontent.com/assets/19521315/19840614/aa4595d4-9ef1-11e6-9dec-634981151337.png)

**Comment by ClaudioESSilva** [comment]
Fixed on commit https://github.com/sqlcollaborative/dbareports/commit/d4bf31bb258df9f6c92f5ffe27338e6912250670

**Comment by SQLDBAWithABeard** [comment]
merged
