### ISSUE TITLE
Unable to add local named instances

### ISSUE THREAD

**Issue by DaniSQL** [sqlcollaborative/dbareports#45]
Tried to add two local SQL 2014 and 2016 instances and got this error:

TCP connection failed for ServerName\SQL2014 trying again without

WARNING: Port could not be determined for "ServerName". Skipping.

**Comment by SQLDBAWithABeard** [comment]
So I running SQLServerManager13.msc opened the missing snap-in for me and looks like all the instances I have are running properly, TCP enabled(dynamic port)

[7:13]  
but querying SELECT local_tcp_port FROM sys.dm_exec_connections returns null.
waitstat [7:14 PM]  
I forced a TCP connection by connecting to tcp:localhost\sql2016 and run the query again and this time it returned the actual TCP port

**Comment by SQLDBAWithABeard** [comment]
This is the same as Issue #1
