### ISSUE TITLE
Creating DB with installer causing failure with permission

### ISSUE THREAD

**Issue by felipeff** [sqlcollaborative/dbareports#51]
Tried to install logged with a sysadmin account, using windows authentication and asking the installer to create the database. The database was created, my account was set as the Owner. 
At a later point script tries to add my account as part of DB_OWNER group, which I'm already, so installer fails with exception:

WARNING: Cannot add XXXXX to XXXX as db_owner.
Exception calling "Create" with "0" argument(s): "Create failed for User XXXXX "
At C:\Program Files\WindowsPowerShell\Modules\dbareports\functions\Install-DbaReports.ps1:700 char:6
+                     $dbuser.Create()
+                     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : FailedOperationException

Had to change database owner and remove myself from db_owner group and try again to continue

**Comment by js0505** [comment]
Hmm This is a new one I have not seen before, can you message us on the slack board so we can assist in debugging?

**Comment by sirsql** [comment]
If a login is sysadmin, and the proxy used for setup matches that login then the database owner will be that login, and this causes the create user statement to fail with the error "The login already has an account under a different name"
