### ISSUE TITLE
Add-DbrServerToInventory.ps1:388 "Input array is longer than the number of columns in this table."

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbareports#54]
Write-Log : Failed to add xyz\MSSQLSERVER to teh datatable - Exception calling "Add" with "13"
argument(s): "Input array is longer than the number of columns in this table."
At
C:\Users\xyz\Documents\WindowsPowerShell\Modules\dbareports\functions\Add-DbrServerToInventory.ps1:388
char:5
                 Write-Log -path $LogFilePath -message "Failed to add $servername\$InstanceNa ...
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log

Something went wrong - The Beard is sad :-( . You can find the install log here C:\Users\xyz\Documents\d
bareports_ADD-DBRServerToInventory_20161122011329.txt

**Comment by SQLDBAWithABeard** [comment]
Fixed with f5e50d486b2dc798fdcd0d53e67e2872ae088ace
