### ISSUE TITLE
Input array is longer than the number of columns in this table

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbareports#62]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Version 0.2.53

Failed to add OTHERSQLSERVER\instancename to the datatable - Exception calling "Add" with "14" argument(s): "Input array is longer than the number of columns in this table."

C:\Users\MYACCOUNT\Documents\WindowsPowerShell\Modules\dbareports\functions\Add-DbrServerToInventory.ps1:371

See attached log. So strange, the servers end up in dbo.instances anyway.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net**

Install from total scratch -- previous database was dropped and Uninstall-DbaReports was ran.

Add-DbrServerToInventory -SqlInstance MYINSTANCE
Add-DbrServerToInventory -SqlInstance OTHERSQLSERVER\instancename -Location MyLocation

**What is the expected behavior?**
Install works without exceptions

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2012. Not recently

Here is the log: [sanitized.txt](https://github.com/sqlcollaborative/dbareports/files/633952/sanitized.txt)

**Comment by SQLDBAWithABeard** [comment]
Hmm @ctrlbold 

I think you have some files left over from a previous installation somehow

I have just installed from gallery version 0.2.53 

get-module dbareports

ModuleType Version    Name                                ExportedCommands                                                                   
---------- -------    ----                                ----------------                                                                   
Script     0.2.53     dbareports                          {Add-DbrAgentJob, Add-DbrCredential, Add-DbrServerToInventory, Get-DbrAgentJob...} 


and then install-dbareports to a new server. Here are my results

The bit that makes me think it is different is this is the relevant part of my install log

> 2016-12-06 13:43:54 INFO: Thanks for installing dbareports! Here are the results of Get-DbrConfig:
> 2016-12-06 13:43:54 INFO: @{SQLServer=DBAREPORTSSERVER; Username=BLAH; LoginType=Windows Authentication; ConfigFile=C:\Users\BLAH\Documents\WindowsPowerShell\Modules\dbareports\dbareports-config.json; DbaReportsVersion=0.0.4; InstallDatabase=dbareports; AgentAccount=BLAH; InstallPath=c:\temp\dbareports; LogPath=c:\temp\dbareports\logs}
> 2016-12-06 13:43:54 INFO: You may now run Add-DbrServerToInventory to add a new server to your inventory.
> 2016-12-06 13:43:56 INFO: Adding DBAREPORTSSERVER to inventory using Add-DbrServerToInventory
> 

that is the end of the file and the script calls add-dbrservertoinventory which will use a separate log file

> 2016-12-06 13:43:56 INFO: Intialised the datatable for dbo.InstanceList
> 2016-12-06 13:43:56 INFO: Added update of bit
> 2016-12-06 13:43:57 INFO: Adding 1 row(s)
> 2016-12-06 13:43:57 INFO: Checking to see if BLAH has access to DBAREPORTSSERVER.
> 2016-12-06 13:43:57 INFO: Lookin' good! BLAH successfully logged in to DBAREPORTSSERVER.
> 2016-12-06 13:43:57 INFO: Populating a few other tables with the info for DBAREPORTSSERVER while we're at it.
> 2016-12-06 13:43:57 INFO: Starting Agent Job Server job
> 2016-12-06 13:43:57 INFO: Starting Windows Server Information job
> 2016-12-06 13:43:57 INFO: Starting SQL Server Information job
> 2016-12-06 13:43:57 INFO: Done!

**Comment by ctrlbold** [comment]
K, ill try again and delete everything, brb

**Comment by ctrlbold** [comment]
I'm a dumbass! That worked :D I think I had the old module in memory. Thank you.
