### ISSUE TITLE
Add Support for Web/Express edition of SSRS

### ISSUE THREAD

**Issue by mrthomsmith** [sqlcollaborative/dbareports#71]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Deploying the [SSRS reports](https://github.com/sqlcollaborative/dbareports/tree/Development/samples/reports/SSRS) causes an error because shared datasets are not supported.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net**
N/a

**What is the expected behavior?**
Option to install reports with no shared datasets

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Affects users of SSRS on Web or Express editions of SQL Server

**Comment by wsmelton** [comment]
@mrthomsmith This repo does not do any work with SSRS are you thinking of [this one possibly](https://github.com/Microsoft/ReportingServicesTools)?
